# LIBRARIES

library(data.table)
library(graphics)
library(sp)
library(grDevices)
library(ggplot2)
library(ggthemes)
library(colormap)
library(lubridate)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(plotly)
library(zoo)
library(gridExtra)
library(viridis)
library(ggmap)
library(raster)
library(gridExtra)
library(scales)